# Generated by Django 5.1.7 on 2025-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
