# Generated by Django 5.1.7 on 2025-05-28 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration', 'User Registration'), ('money_transfer_initiated', 'Money Transfer Initiated'), ('money_transfer_completed', 'Money Transfer Completed'), ('currency_request_update', 'Foreign Currency Request Update'), ('exchange_rate_alert', 'Exchange Rate Alert'), ('payment_received', 'PaymentTransaction Received'), ('escrow_created', 'Escrow Created'), ('settlement_processed', 'Settlement Processed'), ('transaction_issue', 'Transaction Issues or Failures'), ('escrow_flag_admin', 'Admin Escrow Flags / Fraud Alerts'), ('fraud_event', 'Fraud Detection Event')], max_length=64)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
