"""
Django settings for PMF project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.

TWILIO_ACCOUNT_SID = os.getenv("Account_sId")
TWILIO_AUTH_TOKEN = os.getenv("Account_tId")
TWILIO_PHONE_NUMBER = os.getenv("phone_number")
SMS_MODE_API_KEY = os.getenv("smsMode_Api_key")
SMS_URL = os.getenv("sms_url")
BASE_DIR = Path(__file__).resolve().parent.parent

cloudinary.config( 
  cloud_name=os.getenv("CLOUD_NAME"), 
  api_key=os.getenv("CLOUD_API_KEY"), 
  api_secret=os.getenv("CLOUD_API_SECRET") 
)


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w&4y4$(rzm2)n9j*ez*lillfbov6mc=%_^7hx7ia!irqr@8+q9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',
    'django.contrib.staticfiles',
    'rest_framework',
<<<<<<< HEAD:PMF/PMF/settings.py
    'oauth2_provider',
    'rest_framework_simplejwt',

    # apps
    'channels', 
    'accounts',
    'notifications',
    'chatting',
=======
    'oauth2_provider',  
    'rest_framework_simplejwt', 
    "django_celery_beat",
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
    
    # apps
    'apps.accounts',
    'apps.KYC',
    'apps.Transaction',
    'apps.Escrow',
    'apps.PaymentTransaction'
    
    
    
    
>>>>>>> 580101a1e76761a0e66563686e61305b8dbec3af:Backend/PMF/PMF/settings.py
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
       
        # 'rest_framework.permissions.AllowAny',
  
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',  # Only allow authenticated users
    # ],
}
# settings.py

CELERY_BROKER_URL = 'redis://localhost:6380/0'  # Use Redis as a message broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


#static files
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", 
]

ROOT_URLCONF = 'PMF.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PMF.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv("DATABASE_URL"),
        conn_max_age=600,
    )
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'pay_my_fees',
#         'USER': 'mihretu',
#         'PASSWORD': 'ndkBdJmRtxhUTubwcssWdtwHeerbTYwb',
#         'HOST': 'postgres-xmle.railway.internal',
#         'PORT': '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

<<<<<<< HEAD:PMF/PMF/settings.py

# ASGI application
ASGI_APPLICATION = 'PMF.asgi.application'

# Channels Layer Configuration 
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.0", 6379)], 
        },
    },
}
=======
# settings.py
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # Allow all origins for development purposes

# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or another SMTP provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mihretuendeshaw84@gmail.com'
EMAIL_HOST_PASSWORD = 'qymy eawv mzuz kuzq'  # use an app password if using Gmail
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
>>>>>>> 580101a1e76761a0e66563686e61305b8dbec3af:Backend/PMF/PMF/settings.py
