# Generated by Django 5.1.7 on 2025-05-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escrow', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='transaction',
        ),
        migrations.AddField(
            model_name='escrow',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='escrow',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
