# Generated by Django 5.1.7 on 2025-05-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_transactionlog_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransfer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money')], default='paypal', max_length=20),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='purpose',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
