# Generated by Django 5.1.7 on 2025-05-30 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='recipient_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='recipient_full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='recipient_sort_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
