# Generated by Django 5.1.7 on 2025-06-12 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Escrow', '0003_escrow_currency_alter_escrow_status_and_more'),
        ('Transaction', '0006_foreigncurrencyrequest_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='escrow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Escrow.escrow'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='escrow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Escrow.escrow'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_from',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Currency code must be a 3-letter ISO 4217 code (e.g., USD).', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_to',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Currency code must be a 3-letter ISO 4217 code (e.g., USD).', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='foreigncurrencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('in_escrow', 'In Escrow'), ('released', 'Released'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('in_escrow', 'In Escrow'), ('released', 'Released'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
    ]
