# Generated by Django 5.1.7 on 2025-06-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0008_foreigncurrencyrequest_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('base_code', models.CharField(max_length=10)),
                ('rates', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
