# Generated by Django 5.1.7 on 2025-06-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0009_dailyexchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='bank_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='pmf_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='bank_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='pmf_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
