# Generated by Django 5.1.7 on 2025-06-17 14:54

import cloudinary.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0010_foreigncurrencyrequest_bank_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foreigncurrencyrequest',
            name='proof_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='proof_document'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='proof_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='proof_document'),
        ),
        migrations.AlterField(
            model_name='foreigncurrencyrequest',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('ETB', 'Ethiopian Birr'), ('GBP', 'British Pound')], max_length=10),
        ),
        migrations.AlterField(
            model_name='foreigncurrencyrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('telebirr', 'TeleBirr'), ('CBE', 'CBE'), ('chapa', 'Chapa')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='foreigncurrencyrequest',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('ETB', 'Ethiopian Birr'), ('GBP', 'British Pound')], max_length=10),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='CurrencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('target_currency', models.CharField(max_length=10)),
                ('min_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('max_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_interval', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
