# Generated by Django 5.1.7 on 2025-06-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0010_foreigncurrencyrequest_bank_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreigncurrencyrequest',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
