# Generated by Django 5.1.7 on 2025-06-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0011_foreigncurrencyrequest_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyalert',
            name='target_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Central rate used to calculate min/max thresholds', max_digits=12, null=True),
        ),
    ]
