# Generated by Django 5.1.7 on 2025-06-15 17:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0011_alter_foreigncurrencyrequest_transaction_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('target_currency', models.CharField(max_length=10)),
                ('min_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('max_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_interval', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
