# Generated by Django 5.1.7 on 2025-06-18 06:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KYC', '0002_alter_kyc_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='document_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='document_back'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_front',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document_front'),
        ),
    ]
